### ISSUE TITLE
CV AI generative step isn't clear

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#957] opened 2024-09-19 11:11 UTC
**Background**
We see many people struggling with the CV AI generation from different angles: not clear instructions, AI has a limit of trying, and acceptance criteria aren't clear for volunteers.

**Acceptance criteria**
- Research on our ITD Channels and on the ITD Workspace about this step
- Identify the main problems that must be tackled
- Produce a content tackling the main problems
- Ask @kfklein15 to update steps on Dashboard
- Update https://cyf-itd.netlify.app/steps/one/

**Comment by Ara225** [comment] 2024-09-19 17:18
The problem is that the AI is not behaving consitantly. This is of course something to be exspected in our current generation of AI modals but it is a problem for students. I tested and ran into an issue while very carefully followig the instructions and copy pasting the example prompts. Attached thepart  of the chat logs where it went off the rails because I find them funny but I think maybe we should be questioning whether we want to frustrate students with this excercise at this stage
[chat.txt](https://github.com/user-attachments/files/17063442/chat.txt)

**Comment by Ara225** [comment] 2024-09-20 20:46
Have done some thinking, I think that we have a few options:
- Rewrite the intructions from the course so they consistantly work - means making our own fake job content or stealing theirs
- Guide them to a cV creator on the internet
- add guidence to the step page that they should do thinngs slightly diffrently than the course 
- Rethink the process

**Comment by illicitonion** [comment] 2024-09-23 12:56
> The question is that if the goal is them having a CV or them learning how to interact with the AI

I completely agree with the idea that we should focus on one or the other, not both. Splitting this into two steps is probably worthwhile...

For the "How to interact with GenAI" piece, ideally we would put in a bit more nuance around the differences between "I want to use GenAI to help me learn" vs "I want to use GenAI to help me produce something".

Particularly covering things like "When learning (rather than producing), your goal is to understand, not to solve the problem - copying and pasting the solution is not useful", "When learning (rather than producing), try to ask fundamental building-block questions (e.g. 'how to sort an array') not whole-problem questions, and break down whole-problems into building blocks (which maybe the GenAI can help you to do, though ideally you do yourself)", etc.

It's probably not ideal to have our very first task in the course being "Use GenAI" without covering the "but when you're using it to learn, you need to think very differently" piece; we could probably tone-set that better...

**Comment by Ara225** [comment] 2024-09-23 13:28
Thank you :) this has made a few things click in my mind. I think a mini course along the lines of "gen ai for programming without making it a crutch" would be a good idea. The CV element doesn't feel entirely indispensable though so I'll discuss that with the others

**Comment by SallyMcGrath** [comment] 2024-09-24 12:43
Fab discussion!

It doesn't feel like Gen AI for programming fits in ITD. Maybe it's helpful to work through:

What are the goals of ITD?

1. Welcome people to tech with short taster projects
1. Create some tangible products people can use in their life
1. Improve the job prospects of participants by at least one degree (if they don't have a CV, write one; if they don't have a website, build one, if they don't know their English level, find it out)

What are the goals of Step 1?

1. A simple, short (1 hour or less) project that produces a tangible result. This result must be useful to the person in their real life, that will continue past this course, whether they pass ITD or not. 
1. An easy win that encourages people to continue

So it doesn't have to be this step, but it does have to meet these goals. What do you think?

**Comment by SallyMcGrath** [comment] 2024-09-24 12:48
I don't know why it closed this!! Reopened!

**Comment by Ara225** [comment] 2024-09-24 12:56
Thans for this @SallyMcGrath Thosse are some very good points. Put that way, the gen AI element does feel the more disposable of the two. Do you think a plain old guide to building a basic CV would fulfill these goals (in some ways it might do so more as they would get their CV not a CV for an immaginary person) or is there anyother path you would recommend?

**Comment by Ara225** [comment] 2024-09-24 12:56
(i'm suffering from an inability to make my mind up on this)

**Comment by illicitonion** [comment] 2024-09-27 12:47
I like the idea of using some guide to help produce a useful personal CV being the core task! There's generally a lot of low-hanging fruit advice that's useful to most of our trainees.

**Comment by Ara225** [comment] 2024-10-10 18:48
Adding a status update for future reference. I've made a draft that went slightly left field: https://codeyourfuture.slack.com/archives/C07799JJD5E/p1728472620253789?thread_ts=1728472620.253789&cid=C07799JJD5E

**Comment by kfklein15** [comment] 2024-10-15 15:21
@Ara225 , can you give us an update on this, please?

**Comment by Ara225** [comment] 2024-10-15 16:39
Hi, 
I'm done, I'm just waiting till the meeting to go over it with the team. Last week was cancelled

**Comment by kfklein15** [comment] 2024-10-16 20:21
Thanks. If I review it here (or we jump on a call tomorrow) can we get this approved? Or do we need Zachee (Sayo is offline for now)

**Comment by Ara225** [comment] 2024-10-17 10:12
Of course we haven't really agreed a process for approval (probably should) but don't see why not.

**Comment by kfklein15** [comment] 2024-10-18 17:59
[Google doc](https://docs.google.com/document/d/1OrLpB1nH-b60aroS-lqi4sk-7P2CmrvU_QF2IFk9CeM/edit)

**Comment by kfklein15** [comment] 2024-10-18 18:05
@Ara225 to create PR for the curriculum so we have our ITD Portal up-to-date

Use [Hemingway app](https://hemingwayapp.com/) to simplify phrases.

**Closed** 2024-10-24 07:25 UTC
Labels: ITD
