### ISSUE TITLE
1 Slack channel per step

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#1080] opened 2024-10-15 15:03 UTC
**Which module(s) and week(s) does this change affect?**
Module(s): N/A
Week(s): N/A

**What is the work that needs to be done?**
Create 1 channel for every step on ITD Slack channel

**Why is this work important to do?**
so it's easy to manage questions about the same step

**Additional context**
**Who might need to know about this change?**

**Comment by SallyMcGrath** [comment] 2024-10-24 06:40
Dupe of #1054 but less detail on this so closing

**Closed by SallyMcGrath** 2024-10-24 06:40 UTC
Labels: ITD
