### ISSUE TITLE
Coursework projects/exercises updated in line with the curriculum prep work

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#348] opened 2023-10-27 13:04 UTC
## Acceptance criteria

- [ ]  Update coursework tasks for [Module-JS3](https://github.com/CodeYourFuture/Module-JS3) inline with work for the new JS3 Week 3
- [ ] Update coursework issues for Module-JS3

**Comment by 40thieves** [comment] 2023-11-23 19:50
We think this is a dupe of #344, closing.

**Closed by 40thieves** 2023-11-23 19:50 UTC
